name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line Script
      run: echo Hello, world!
      
    - name: Run a multy-line scripts
      run: |
        echo Add other actionn to build,
        echo test, and deploy your project.
    
    
